### ISSUE TITLE
Put SRConfigs files inside an SRConfigs folder

### ISSUE THREAD

**Issue by betsruner** [p2sr/srconfigs#56]
If all the SRConfigs files were moved into a SRConfigs folder (except autoexec ofc) it would make uninstalling/reinstalling a bunch easier, as well as finding specific files.

**Comment by ThisAMJ** [comment]
It would certainly decrease confusion (except for people who update and now have two sets of srconfigs) but IMO if you want to easily identify srconfigs you should just put it in a separate game path. This change feels like an unnecessary breaking change. Potentially I could include uninstall bat/sh scripts in a 'srconfigs' folder?

[P2 Common Tutorial](https://youtu.be/FmJ1OcKc7Ag)

Personally I have my gameinfo so that my common files load on top of srconfigs on top of game files
